name: finance-tracker
type: laravel
docroot: public
php_version: "8.5"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "10.11"
use_dns_when_possible: true
composer_version: "2"
web_environment: []
corepack_enable: false
host_db_port: 60000 
web_extra_exposed_ports:
  - name: reverb
    container_port: 8080
    https_port: 8080
    http_port: 8081
web_extra_daemons:
  - name: reverb
    command: "cd ${DDEV_COMPOSER_ROOT} && php artisan reverb:start"
    directory: /var/www/html
disable_http2: true
